import Head from "next/head";
import { Inter } from "next/font/google";
import { HomePage } from "@/src/components/home/home-page";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data} />
    </>
  );
}

// server side rendering
// this function needs to be separate from component
// it cannot go inside component
// this will run on server only, it never runs on client
// it will run before above component
export async function getServerSideProps() {
  // const res = await fetch("url");
  // const data = res.json();
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}

// static generation
// next pregenerates all pages during build time
// when we build our application, we pre-generate pages before we deploy it
